Resources:
  Namespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      AdminUsername: "tunde.h.rahman"
      AdminUserPassword: "Tunde123!#Tunde123!#"
      DbName: TrafficData
      NamespaceName: "traffic-data-namespace"
      IamRoles: 
       - MyRedshiftRole
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "redshift.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      RoleName: MyRedshiftRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

