Resources:
  NameSpaceResource:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      AdminUsername: "tunde.h.rahman"
      AdminUserPassword: "Tunde123!#Tunde123!#"
      DbName: TrafficData
      NamespaceName: "traffic-data-namespace"
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "redshift.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      RoleName: MyRedshiftRole

